#!/usr/bin/env python3
"""Refresh the MITRE ATLAS snapshot used by this skill and audit the ATLAS IDs the references cite.

Usage:
    python3 scripts/refresh_atlas.py                       # download ATLAS.yaml, write references/atlas-techniques.md, audit
    python3 scripts/refresh_atlas.py --atlas PATH          # offline, from a local ATLAS.yaml
    python3 scripts/refresh_atlas.py --check-only          # audit cited IDs, write nothing

Source: https://github.com/mitre-atlas/atlas-data (dist/ATLAS.yaml). ATLAS is released under the
Apache 2.0 licence; the generated snapshot carries the source version and download date.

What it does:
  1. Writes `references/atlas-techniques.md`: every tactic and technique (ID, name, tactic, maturity,
     ATT&CK reference) in the current ATLAS release, dated and versioned. This is the file to cite for
     technique names; it replaces reliance on the names memorised in the hand-curated mappings.
  2. Audits every `AML.T####[.###]` ID cited in `references/*.md` and reports IDs that no longer exist
     in ATLAS, IDs whose name in ATLAS differs from the name written beside them in the reference, and
     techniques ATLAS added since the last snapshot that no reference cites. It never rewrites the
     hand-curated mapping files; the audit output tells the maintainer what to reconcile by hand.

Requires PyYAML (`pip install pyyaml`).
"""
from __future__ import annotations

import argparse
import datetime as dt
import re
import sys
import urllib.request
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    print("PyYAML is required: pip install pyyaml", file=sys.stderr)
    sys.exit(2)

ATLAS_URL = "https://raw.githubusercontent.com/mitre-atlas/atlas-data/main/dist/ATLAS.yaml"
ROOT = Path(__file__).resolve().parent.parent
REFS = ROOT / "references"
OUT = REFS / "atlas-techniques.md"
ID_RE = re.compile(r"(?:AML\.)?T0\d{3}(?:\.\d{3})?")  # bare T0xxx shorthand counts once a cell has an AML. prefix in play


def load_atlas(path: str | None) -> dict:
    if path:
        return yaml.safe_load(Path(path).read_text(encoding="utf-8"))
    with urllib.request.urlopen(ATLAS_URL, timeout=60) as r:
        return yaml.safe_load(r.read().decode("utf-8"))


def write_snapshot(atlas: dict) -> tuple[dict[str, dict], dict[str, str]]:
    m = atlas["matrices"][0]
    tactics = {t["id"]: t["name"] for t in m["tactics"]}
    techs = {t["id"]: t for t in m["techniques"]}
    today = dt.date.today().isoformat()
    lines = [
        "# MITRE ATLAS technique snapshot",
        "",
        f"Generated by `scripts/refresh_atlas.py` on {today} from ATLAS {atlas.get('version')} ({ATLAS_URL}). "
        "Do not edit by hand; re-run the script. Cite technique IDs from this file; the hand-curated mappings in "
        "`threat-technique-and-control-library.md` and `framework-crosswalk.md` supply the MAESTRO layer, this file supplies the current ATLAS name.",
        "",
        "## Tactics",
        "",
        "| ID | Name | ATT&CK |",
        "|---|---|---|",
    ]
    for t in m["tactics"]:
        att = (t.get("ATT&CK-reference") or {}).get("id", "")
        lines.append(f"| {t['id']} | {t['name']} | {att} |")
    lines += ["", "## Techniques", "", "| ID | Name | Tactic(s) | Maturity | ATT&CK | Modified |", "|---|---|---|---|---|---|"]
    for t in sorted(m["techniques"], key=lambda x: x["id"]):
        tac = "; ".join(tactics.get(x, x) for x in t.get("tactics", [])) if t.get("tactics") else ""
        if not tac and "." in t["id"]:
            parent = techs.get(t["id"].rsplit(".", 1)[0], {})
            tac = "; ".join(tactics.get(x, x) for x in parent.get("tactics", []))
        att = (t.get("ATT&CK-reference") or {}).get("id", "")
        lines.append(f"| {t['id']} | {t['name']} | {tac} | {t.get('maturity', '')} | {att} | {t.get('modified_date', '')} |")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return techs, tactics


def audit(techs: dict[str, dict], strict: bool = False) -> int:
    cited: dict[str, set[str]] = {}
    name_mismatch = []
    for f in sorted(REFS.glob("*.md")):
        if f.name == OUT.name:
            continue
        text = f.read_text(encoding="utf-8")
        for mm in ID_RE.finditer(text):
            tid = mm.group(0) if mm.group(0).startswith("AML.") else "AML." + mm.group(0)
            cited.setdefault(tid, set()).add(f.name)
            # name written right after the ID on the same line, e.g. "AML.T0051 LLM Prompt Injection"
            line_start = text.rfind("\n", 0, mm.start()) + 1
            in_table = text[line_start:line_start + 1] == "|"
            tail = text[mm.end(): mm.end() + 80].split("|")[0].split("\n")[0].strip(" :–-")
            t = techs.get(tid)
            if in_table and t and tail and not tail.lower().startswith(t["name"].lower()[: min(12, len(t["name"]))]) and tail[:1].isalpha():
                name_mismatch.append((f.name, tid, tail[:40], t["name"]))
    missing = sorted(i for i in cited if i not in techs)
    print(f"ATLAS techniques in release: {len(techs)}; distinct IDs cited in references: {len(cited)}")
    print(f"\nCited IDs absent from current ATLAS ({len(missing)}):")
    for i in missing:
        print(f"  {i}  <- {', '.join(sorted(cited[i]))}")
    seen = set()
    name_mismatch = [x for x in name_mismatch if not (x in seen or seen.add(x))]
    print(f"\nName beside ID differs from ATLAS name ({len(name_mismatch)}), reconcile by hand "
          "('abbrev?' = shares a significant word with the ATLAS name, probably shorthand; unmarked = likely a wrong ID or a renamed technique):")
    for f, i, written, real in name_mismatch:
        w = {x.lower() for x in re.findall(r"[A-Za-z]{4,}", written)} - {"model", "attack", "data"}
        r = {x.lower() for x in re.findall(r"[A-Za-z]{4,}", real)}
        tag = "abbrev?" if w & r else ""
        print(f"  {f}: {i} written '{written}' / ATLAS '{real}'  {tag}")
    uncited = [t for t in techs.values() if t["id"] not in cited and not re.search(r"\.\d{3}$", t["id"])]
    print(f"\nTop-level techniques not cited anywhere in references ({len(uncited)}); newest first:")
    for t in sorted(uncited, key=lambda x: str(x.get("modified_date", "")), reverse=True)[:25]:
        print(f"  {t['id']}  {t['name']}  (modified {t.get('modified_date', '')})")
    unmarked = 0
    for f, i, written, real in name_mismatch:
        w = {x.lower() for x in re.findall(r"[A-Za-z]{4,}", written)} - {"model", "attack", "data"}
        r = {x.lower() for x in re.findall(r"[A-Za-z]{4,}", real)}
        if not (w & r):
            unmarked += 1
    if strict and unmarked:
        print(f"\nSTRICT: {unmarked} unmarked name mismatch(es); packaging gate fails.")
    return 1 if missing or (strict and unmarked) else 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--atlas", help="local ATLAS.yaml (offline)")
    ap.add_argument("--check-only", action="store_true")
    ap.add_argument("--strict", action="store_true", help="also fail on unmarked name mismatches (packaging gate)")
    args = ap.parse_args()
    atlas = load_atlas(args.atlas)
    if args.check_only:
        m = atlas["matrices"][0]
        techs = {t["id"]: t for t in m["techniques"]}
    else:
        techs, _ = write_snapshot(atlas)
        print(f"wrote {OUT.relative_to(ROOT)} (ATLAS {atlas.get('version')})")
    return audit(techs, strict=args.strict)


if __name__ == "__main__":
    sys.exit(main())
